services:
  db:
    image: postgres:16
    container_name: studentapp-db
    restart: always
    environment:
      POSTGRES_DB: studentapp
      POSTGRES_USER: studentadmin
      POSTGRES_PASSWORD: studentpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
