    - name: Update network
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/netplan.yml.j2"
        dest: /etc/netplan/00-installer-config.yaml
        mode: "0644"

    - name: Apply netplan
      ansible.builtin.command: netplan apply
      changed_when: true